[DOPS-1561]: Add publish to public nexus repo for Iroha2
hyperledger/iroha-java pull request #196
Opened 2022-02-01 04:43 UTC by wpi86

# Task

[DOPS-1561]: Add publish to public nexus repo for iroha2

## Changes

1. Add publish to public nexus repo 

## Author

Signed-off-by: Pavel Varfolomeev wpi86@yandex.ru

[DOPS-1561]: https://soramitsu.atlassian.net/browse/DOPS-1561

2022-02-01 06:35 UTC, arndey approved these changes

2022-02-01 07:13 UTC, Mingela requested changes
-1.0-SNAPSHOT should not definitely be hardcoded
if that's produced from the current repo state please try editing that as well

2022-02-01 14:54 UTC, wpi86 commented
> -1.0-SNAPSHOT should not definitely be hardcoded if that's produced from the current repo state please try editing that as well In case we change it somehow in the future CI breaks

Fixed

2022-02-02 06:10 UTC, Mingela approved these changes

2022-02-03 06:16 UTC, merged