Iroha-213: changed schema for trigger events and added tests
hyperledger/iroha-java pull request #214
Opened 2022-04-20 13:59 UTC by gv-timur

Signed-off-by: Guskov Timur <guskov@soramitsu.co.jp>

changed schema for trigger events and added tests

2022-04-21 08:52 UTC, arndey commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/TriggersTest.kt
> +        val domainId = "wonderland".asDomainId()
You can use DEFAULT_DOMAIN_ID here

2022-04-21 08:59 UTC, arndey commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/TriggersTest.kt
> +        newQuantity = QueryBuilder.findDomainById(domainId)
It repeats 3 times, please consider create separate func or anonymous func like in test `InstructionsTest.check assets with type Fixed are properly minted and burned`

2022-04-21 09:00 UTC, arndey commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/TriggersTest.kt
> +        assertEquals(2, assetDefinitions.size)
I think it will be better to move all checks out of this function to test body

2022-04-21 12:01 UTC, Mingela commented on modules/client/src/main/kotlin/jp/co/soramitsu/iroha2/transaction/Instructions.kt
> +     * Instruction for trigger to run after some asset definition for account is created
I don't think we need to have this defined on a SDK core level, should be moved to some test classes code

2022-04-21 12:01 UTC, Mingela commented on modules/client/src/main/kotlin/jp/co/soramitsu/iroha2/transaction/Instructions.kt
> +     * Instruction for pre commit trigger to run after every transaction
This too, leave only generic methods here

2022-04-21 12:02 UTC, Mingela commented on modules/client/src/main/kotlin/jp/co/soramitsu/iroha2/transaction/Instructions.kt
> +     * Instruction for pre commit trigger to run after every transaction
though this is quite generic and it's okay to leave this one here

2022-04-21 12:08 UTC, Mingela requested changes
please consider the comments above

2022-04-22 10:34 UTC, Mingela approved these changes

2022-04-22 10:56 UTC, merged