feature (issue 320): added block streaming support + test
hyperledger/iroha-java pull request #328
Opened 2023-05-02 18:09 UTC by gv-timur

added block streaming support + test

2023-05-03 08:20 UTC, arndey commented on modules/client/src/main/kotlin/jp/co/soramitsu/iroha2/client/Iroha2Client.kt
> +                    logger.debug("Received frame: $frame")
```suggestion
                    logger.debug("Received frame: {}", frame)
```

2023-05-03 08:24 UTC, arndey commented on modules/client/src/main/kotlin/jp/co/soramitsu/iroha2/client/Iroha2Client.kt
> +                for (frame in incoming) {
perfect place to use kotlin channels or flows

2023-05-03 08:29 UTC, arndey commented on modules/client/src/main/kotlin/jp/co/soramitsu/iroha2/client/Iroha2Client.kt
> +                for (frame in incoming) {
may need to get rid of the launch above

2023-05-03 08:51 UTC, arndey commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/BlockStreamTest.kt
> +        fun checkSecondBlock(blockMessage: VersionedBlockMessage) {
please don't create function in the middle of another function
if it's necessary to keep function in function - move it to the top

2023-05-03 08:52 UTC, arndey commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/BlockStreamTest.kt
> +        val registerDomain = instructions[0].cast<Instruction.Register>()
i think we might have some extract function fo that
if not - please create it

2023-05-03 08:52 UTC, arndey commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/BlockStreamTest.kt
> +        assertEquals("foo@wonderland", instructions[3].cast<Instruction.Register>().extractAccount().id.asString())
please use const DEFAULT_DOMAIN

2023-05-03 08:53 UTC, arndey commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/BlockStreamTest.kt
> +            assertEquals("bob", instructionAccount)
please use const BOB_ACCOUNT_NAME
if you need it as string - please create new const

2023-05-03 08:54 UTC, arndey commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/BlockStreamTest.kt
> +            val newAssetDefinition = instructions[0].cast<Instruction.Register>()
use extract fun

2023-05-03 08:54 UTC, arndey commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/BlockStreamTest.kt
> +        val genesis = "genesis"
create const

2023-05-03 08:55 UTC, arndey commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/BlockStreamTest.kt
> +        val defaultDomain = "wonderland"
use const

2023-05-03 08:57 UTC, arndey commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/BlockStreamTest.kt
> +        fun checkSecondBlock(blockMessage: VersionedBlockMessage) {
also I honesty don't understand the function name

2023-05-03 08:57 UTC, arndey requested changes
changes

2023-05-03 09:43 UTC, Mingela commented on modules/client/src/main/kotlin/jp/co/soramitsu/iroha2/client/Iroha2Client.kt
> +    fun subscribeToBlockStream(startFromBlock: Long, blocksCount: Int): CompletableDeferred<List<VersionedBlockMessage>> {
Please expand the issue description (or create new one) with the specific requirements, though that's exactly what I requested in the chat when the task came in 'to-do' 😢

2023-05-03 09:48 UTC, Mingela reviewed
Andrey's comments seem valid, I don't have more than those.

As for the API itself it'd great to return something like `Flux` (Reactor) or `Observable` (RxJava) or at least have a method expecting a logic to be applied to each block, i.e. `blockStream<T>(startFromBlock:Long, (VersionedBlockMessage) -> (T))`

2023-05-05 11:10 UTC, Mingela approved these changes

2023-05-05 14:39 UTC, Mingela commented
Work to be continued within https://github.com/hyperledger/iroha-java/issues/330

2023-05-05 14:39 UTC, merged