feature (issue 268): fixed deserializer test
hyperledger/iroha-java pull request #339
Opened 2023-06-05 05:59 UTC by gv-timur

fixed deserializer test
deserializers refactoring

2023-06-06 10:29 UTC, Mingela commented
I'd say that's okay to start with, what do you think @arndey? though let's add more within the PR first based on other genesis blocks as you mentioned

2023-06-07 04:17 UTC, arndey commented on modules/block/src/test/kotlin/jp/co/soramitsu/iroha2/DeserializerTest.kt
> +        assert(block.transactions.first().isi.size == 7)
left a comment why 7

2023-06-07 04:24 UTC, arndey approved these changes

2023-06-09 06:29 UTC, arndey commented on modules/block/src/main/kotlin/jp/co/soramitsu/iroha2/Serde.kt
> +    val clazz = when (param) {
deserves to be executed in a separate private method

2023-06-09 06:29 UTC, arndey commented on modules/block/src/main/kotlin/jp/co/soramitsu/iroha2/Serde.kt
> +        return when (clazz) {
and this

2023-06-09 06:31 UTC, arndey commented on modules/block/src/main/kotlin/jp/co/soramitsu/iroha2/Serde.kt
> +    return when (arg) {
and this

2023-06-09 06:32 UTC, arndey commented on modules/block/src/main/kotlin/jp/co/soramitsu/iroha2/Serde.kt
> +    val arg = mapper.convertValue(definitionId.value, "jp.co.soramitsu.iroha2.generated.datamodel.permission.token.TokenId".asClass()) as TokenId
arg, arg2, arg3 -> smth like tokenId, name, value

2023-06-09 06:32 UTC, arndey commented on modules/block/src/test/kotlin/jp/co/soramitsu/iroha2/DeserializerTest.kt
> +//        assertEquals(initialJson, newJson)
?

2023-06-09 06:33 UTC, arndey commented on modules/block/src/test/kotlin/jp/co/soramitsu/iroha2/DeserializerTest.kt
> +//        assertEquals(initialJson, newJson)
?

2023-06-09 06:33 UTC, arndey requested changes
some comments

2023-06-13 06:24 UTC, Mingela approved these changes

2023-06-13 08:45 UTC, arndey approved these changes

2023-06-16 10:04 UTC, merged