feature (issue#113) client-side load balancing
hyperledger/iroha-java pull request #356
Opened 2023-07-07 08:30 UTC by arndey

2023-07-10 11:41 UTC, Mingela requested changes
please refactor to supportable abstractions

2023-07-10 11:41 UTC, Mingela commented on modules/admin-client/src/test/kotlin/jp/co/soramitsu/iroha2/ClientTest.kt
> +            urls.add(config["TORII"]!!.cast<Map<String, String>>()["API_URL"]!!)
how about defining the consts somewhere instead?

2023-07-10 11:41 UTC, Mingela commented on modules/client/src/main/kotlin/jp/co/soramitsu/iroha2/client/Iroha2Client.kt
> +    protected fun getTelemetryUrl() = getUrls().second
could you create a meaningful class instead of just `Pair.first()/second()`

2023-07-10 11:41 UTC, Mingela commented on modules/client/src/main/kotlin/jp/co/soramitsu/iroha2/client/Iroha2Client.kt
> +    private fun getUrls() = when (lastRequestedPeerIdx) {
could this be a part of an implementation of some 'BalancingStrategy' interface?

2023-07-10 11:41 UTC, Mingela commented on modules/client/src/main/kotlin/jp/co/soramitsu/iroha2/client/Iroha2Client.kt
> +            urls[lastRequestedPeerIdx!!]
how about healthcheck before sending a request? can be an optional field of  the strategy I mentioned

2023-07-11 15:58 UTC, Mingela approved these changes

2023-07-12 06:06 UTC, gv-timur approved these changes

2023-07-12 06:16 UTC, merged