Add annotations
hyperledger/iroha-java pull request #436
Opened 2024-09-26 13:40 UTC by troferoller

2024-10-01 10:54 UTC, alexstroke1 requested changes

2024-10-01 10:54 UTC, alexstroke1 commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/InstructionsTest.kt
> +    @Story("Account registers a domain manualy")
If the test is disabled, it doesn't need to be marked up. This is probably just an example.

2024-10-01 10:54 UTC, alexstroke1 commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/InstructionsTest.kt
> +    @Story("Account queries an assets with response given fetch size")
Let's don't touch disabled I think

2024-10-01 10:54 UTC, alexstroke1 commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/InstructionsTest.kt
> +    @Feature("Accounts")
I don't agree. This test checks the correctness of loading iroha with different genesis. In fact it is running iroha with different starting configurations. I think it is possible to return @Feature(“Configurations”).

2024-10-01 10:54 UTC, alexstroke1 commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/InstructionsTest.kt
> +    @Story("Account send multiple instructions")
```suggestion
    @Story("Initiator starts network with multiple genesis")
```

2024-10-01 10:54 UTC, alexstroke1 commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/InstructionsTest.kt
> +    @SdkTestId("account_send_multiple_instructions")
```suggestion
    @SdkTestId("initiator_start_network_with_multiple_genesis")
```

2024-10-01 10:54 UTC, alexstroke1 commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/InstructionsTest.kt
> +    @Feature("Query")
```suggestion
    @Feature("Configurations")
```

2024-10-01 10:54 UTC, alexstroke1 commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/InstructionsTest.kt
> +    @Story("Query find all accounts in genesis and apply it")
```suggestion
    @Story("Initiator starts network with fat genesis")
```

2024-10-01 10:54 UTC, alexstroke1 commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/InstructionsTest.kt
> +    @SdkTestId("query_all_accounts_in_genesis")
```suggestion
    @SdkTestId("initiator_start_network_with_fat_genesis")
```

2024-10-01 10:54 UTC, alexstroke1 commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/PeerTest.kt
> +    @Disabled
why disabled?

2024-10-01 10:54 UTC, alexstroke1 commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/PeerTest.kt
> +    @Story("")
Let's just don't touch PeerTest yet.

2024-10-03 07:45 UTC, troferoller commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/InstructionsTest.kt
> +    @Story("Account queries an assets with response given fetch size")
Set as disabled cuse of dont understanding for any story to correlate

2024-10-04 10:34 UTC, alexstroke1 requested changes

2024-10-04 10:34 UTC, alexstroke1 commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/InstructionsTest.kt
> +    @SdkTestId("account_registers_domain_manual_via_docker_compose")
I think let's not mark up tests that are disabled and are examples.

2024-10-04 10:34 UTC, alexstroke1 commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/InstructionsTest.kt
> +    @Story("Account queries an assets with response given fetch size")
```suggestion
    @Story("Account queries an assets with custom fetch size")
```

2024-10-04 10:34 UTC, alexstroke1 commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/InstructionsTest.kt
> +    @SdkTestId("query_an_assets_with_respond_given_fetch_size")
```suggestion
    @SdkTestId("query_an_assets_with_custom_fetch_size")
```

2024-10-04 10:34 UTC, alexstroke1 commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/PeerTest.kt
> +    @Story("Round-robin load balancing")
Let's don't touch PeerTest.kt yet.

2024-10-09 05:24 UTC, troferoller commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/InstructionsTest.kt
> +    @Story("Account registers a domain manualy")
resolved

2024-10-09 05:24 UTC, troferoller commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/InstructionsTest.kt
> +    @Feature("Accounts")
resolved

2024-10-09 05:25 UTC, troferoller commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/InstructionsTest.kt
> +    @Story("Account send multiple instructions")
resolved

2024-10-09 05:29 UTC, troferoller commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/InstructionsTest.kt
> +    @SdkTestId("account_send_multiple_instructions")
resolved

2024-10-09 05:35 UTC, troferoller commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/InstructionsTest.kt
> +    @Story("Query find all accounts in genesis and apply it")
resolved

2024-10-09 05:37 UTC, troferoller commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/PeerTest.kt
> +    @Disabled
resolved

2024-10-09 05:37 UTC, troferoller commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/PeerTest.kt
> +    @Story("")
resolved

2024-10-09 05:38 UTC, troferoller commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/InstructionsTest.kt
> +    @SdkTestId("account_registers_domain_manual_via_docker_compose")
resolved by deleting annotations

2024-10-09 05:40 UTC, troferoller commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/InstructionsTest.kt
> +    @SdkTestId("query_an_assets_with_respond_given_fetch_size")
resolved

2024-10-09 05:40 UTC, troferoller commented on modules/client/src/test/kotlin/jp/co/soramitsu/iroha2/PeerTest.kt
> +    @Story("Round-robin load balancing")
resolved

2024-10-16 10:34 UTC, alexstroke1 approved these changes

2024-10-17 11:49 UTC, arndey approved these changes

2024-10-17 12:47 UTC, merged